// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tendril.Data;

#nullable disable

namespace Tendril.Data.Migrations
{
    [DbContext(typeof(TendrilDbContext))]
    [Migration("20251119014257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.HasIndex("VenueId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScrapedEventRaw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScrapedEventRaw", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperAttemptHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExtractedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperAttemptHistory", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDynamic")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LastFailureUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSuccessUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("ScraperDefinition", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperMappingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OutputField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransformArgsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransformType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperMappingRule", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperSelector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Multiple")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperSelector", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Venue", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Event", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "Scraper")
                        .WithMany()
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tendril.Core.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId");

                    b.Navigation("Scraper");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScrapedEventRaw", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany()
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperAttemptHistory", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("AttemptHistory")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.Venue", "Venue")
                        .WithMany("Scrapers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperMappingRule", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("MappingRules")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperSelector", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("Selectors")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.Navigation("AttemptHistory");

                    b.Navigation("MappingRules");

                    b.Navigation("Selectors");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Scrapers");
                });
#pragma warning restore 612, 618
        }
    }
}
