// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tendril.Data;

#nullable disable

namespace Tendril.Data.Migrations
{
    [DbContext(typeof(TendrilDbContext))]
    [Migration("20260113025106_AddEventRevisionAttemptHistoryId")]
    partial class AddEventRevisionAttemptHistoryId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TicketUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.HasIndex("VenueId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.EventRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttemptHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RawEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptHistoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("RawEventId");

                    b.ToTable("EventRevision", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScrapedEventRaw", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawDataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ScrapedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ScraperAttemptHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ScraperAttemptHistoryId");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScrapedEventRaw", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperAttemptHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Created")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("EndTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Errored")
                        .HasColumnType("int");

                    b.Property<int>("Extracted")
                        .HasColumnType("int");

                    b.Property<int>("Mapped")
                        .HasColumnType("int");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Skipped")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.Property<int>("Updated")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperAttemptHistory", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractionStrategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LastFailureUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastSuccessUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaginationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("ScraperDefinition", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperMappingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CombineWithField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstantValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RegexPattern")
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RegexReplacement")
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SplitDelimiter")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransformType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperMappingRule", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperSelector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ChildScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Delay")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InteractionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaginationTrigger")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Root")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScraperDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ScraperDefinitionId");

                    b.ToTable("ScraperSelector", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Venue", (string)null);
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Event", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "Scraper")
                        .WithMany()
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tendril.Core.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId");

                    b.Navigation("Scraper");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.EventRevision", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperAttemptHistory", "AttemptHistory")
                        .WithMany("Revisions")
                        .HasForeignKey("AttemptHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tendril.Core.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tendril.Core.Domain.Entities.ScrapedEventRaw", "RawEvent")
                        .WithMany()
                        .HasForeignKey("RawEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AttemptHistory");

                    b.Navigation("Event");

                    b.Navigation("RawEvent");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScrapedEventRaw", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.Event", "Event")
                        .WithMany("ScrapedEventRaws")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tendril.Core.Domain.Entities.ScraperAttemptHistory", "ScraperAttemptHistory")
                        .WithMany("ScrapedEventRaws")
                        .HasForeignKey("ScraperAttemptHistoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany()
                        .HasForeignKey("ScraperDefinitionId");

                    b.Navigation("Event");

                    b.Navigation("ScraperAttemptHistory");

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperAttemptHistory", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("AttemptHistory")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.Venue", "Venue")
                        .WithMany("Scrapers")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperMappingRule", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("MappingRules")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperSelector", b =>
                {
                    b.HasOne("Tendril.Core.Domain.Entities.ScraperDefinition", "ScraperDefinition")
                        .WithMany("Selectors")
                        .HasForeignKey("ScraperDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScraperDefinition");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Event", b =>
                {
                    b.Navigation("ScrapedEventRaws");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperAttemptHistory", b =>
                {
                    b.Navigation("Revisions");

                    b.Navigation("ScrapedEventRaws");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.ScraperDefinition", b =>
                {
                    b.Navigation("AttemptHistory");

                    b.Navigation("MappingRules");

                    b.Navigation("Selectors");
                });

            modelBuilder.Entity("Tendril.Core.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Scrapers");
                });
#pragma warning restore 612, 618
        }
    }
}
